endpoints:
  - name: Github status 
    group: internal
    url: "https://github.com/"
    interval: 5m
    conditions:
      - "[STATUS] == 200"

  - name: Cloudflare
    group: internal
    url: "https://example.org/"
    interval: 5m
    conditions:
      - "[STATUS] == 200"

  - name: Cloudflare dns check
    url: "1.1.1.1" # Address of the DNS server to use
    interval: 5m
    dns:
      query-name: "example.com"
      query-type: "A"
    conditions:
      - "[BODY] == pat(*.*.*.*)"  # Matches any IPv4 address
      - "[DNS_RCODE] == NOERROR"

  - name: check-domain-expiration
    url: "https://kristenhaslam.com/"
    interval: 1h
    conditions:
      - "[DOMAIN_EXPIRATION] > 720h"
