name: post deploy health check

on:
  workflow_run:
    workflows: ["Terraform deployment"]
    types:
      - completed
    branches: [main]
jobs:
  health-check:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    
    steps:

      - name: wait for gatus to stabilize
        run: sleep 30

      - name: Post-deploy health check
        run: curl -f https://kristenhaslam.com/health