name: Terraform deployment 

on: [push]

permissions:
       id-token: write
       contents: read

jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
            run:
               working-directory: infra


        steps:

        - name: checkout code
          uses: actions/checkout@v2 

        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v6.2.3
          with:
            role-to-assume: ${{ vars.TERRAFORM_ROLE}}
            aws-region: eu-west-2

        -  name: Setup Terraform
           uses: hashicorp/setup-terraform@v4


        - name: Terraform formatting
          run: |
              terraform init
              terraform fmt 
              terraform validate
              


        -  name: Terraform plan
           run:
           env:
            TF_VAR_cloudflare_token: ${{ secrets.CLOUDFLARE_TOKEN }}
            TF_VAR_cloudflare_zone_id: ${{ vars.CLOUDFLARE_ZONE_ID }}  
              
              terraform plan

        - name: Run terraform apply
          env:
            TF_VAR_cloudflare_token: ${{ secrets.CLOUDFLARE_TOKEN }}
            TF_VAR_cloudflare_zone_id: ${{ vars.CLOUDFLARE_ZONE_ID }}
          run:
              terraform apply         

            
        